services :
  db:
    container_name: pg-student
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_123
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: pg-adminer-student
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data :